import sys
import re

file_path = 'src/pages/ImportExport.tsx'
with open(file_path, 'r') as f:
    code = f.read()

import_line = "import { loadPremiumFonts, applyPremiumHeader, applyPremiumFooter, premiumTableStyles } from '../lib/pdfTheme';\n"
if "pdfTheme" not in code:
    code = code.replace("import jsPDF from 'jspdf';", "import jsPDF from 'jspdf';\n" + import_line)

def replace_pdf_generation(match):
    return """        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        updateProgress(50, 'Adding report content...');
        await loadPremiumFonts(doc);
        applyPremiumHeader(doc, 'Complete Financial Ledger', 'System Export');
        
        doc.setFontSize(14);
        doc.setFont('Roboto', 'bold');
        doc.text('ACCOUNT SUMMARY', 14, 45);
        
        doc.setFontSize(11);
        doc.setFont('Roboto', 'normal');
        const amountX = 100;
        doc.text('Current Balance:', 14, 55);
        doc.text(`Rs. ${store.currentBalance.toLocaleString('en-IN')}`, amountX, 55, { align: 'right' });
        doc.text('Total Income:', 14, 62);
        doc.text(`Rs. ${store.totalReceived.toLocaleString('en-IN')}`, amountX, 62, { align: 'right' });
        doc.text('Total Expenses:', 14, 69);
        doc.text(`Rs. ${store.totalSent.toLocaleString('en-IN')}`, amountX, 69, { align: 'right' });
        doc.text('Total Savings:', 14, 76);
        doc.text(`Rs. ${(store.totalReceived - store.totalSent).toLocaleString('en-IN')}`, amountX, 76, { align: 'right' });
        doc.text('Pending Amount:', 14, 83);
        doc.text(`Rs. ${store.totalPending.toLocaleString('en-IN')}`, amountX, 83, { align: 'right' });
        
        updateProgress(70, 'Adding transaction table...');
        
        doc.setFontSize(12);
        doc.setFont('Roboto', 'bold');
        doc.text('LEDGER RECORDS', 14, 98);
        
        const tableData = store.transactions.map(t => [
          formatDate(t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date, store.generalSettings?.timezone),
          t.type.toUpperCase(),
          t.personName,
          t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
          `Rs. ${t.amount.toLocaleString('en-IN')}`,
          t.type === 'pending' ? (t as PendingMoney).status : 'COMPLETED'
        ]);
        
        doc.autoTable({
          startY: 104,
          head: [['Date', 'Type', 'Person/Entity', 'Description', 'Amount', 'Status']],
          body: tableData,
          ...premiumTableStyles,
        });
        
        applyPremiumFooter(doc, 'Complete Financial Ledger');
"""

# The match pattern finds the instantiation and ends at the text footer
pattern = re.compile(r'const doc = new jsPDF\(\);.*?doc\.text\(\'Generated by SmartLedger\', 14, doc\.internal\.pageSize\.height - 10\);', re.DOTALL)
code = pattern.sub(replace_pdf_generation, code)

with open(file_path, 'w') as f:
    f.write(code)

print("Patched ImportExport")
